version: "3.8"

services:
  database:
    image: mysql:latest
    container_name: VM_MYSQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mymysql
      MYSQL_DATABASE: VOLUNTEER_MANAGEMENT
    command: --port=4444
    volumes:
      - database_data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "4444:4444"

  backend:
    build: ./backend
    container_name: VM_BACKEND
    restart: always
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PORT: 4444  # Tell backend to use port 4444
      MYSQL_PASSWORD: mymysql
      MYSQL_DATABASE: VOLUNTEER_MANAGEMENT
      JWT_SECRET: my_super_secret_jwt_key
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["node", "app.js"]

  frontend:
    build: ./frontend
    container_name: VM_FRONTEND
    restart: always
    depends_on:
      - backend
    ports:
      - "3333:3333"
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: ["npm", "run", "dev"]

  nginx:
    image: nginx:latest
    container_name: VM_NGINX
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  database_data:
 